server:
  port: 8080

spring:
  application:
    name: myapp

  # Vault Configuration
  cloud:
    vault:
      uri: http://vault:8200
      authentication: kubernetes
      kubernetes:
        role: myapp
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kv:
        enabled: true
        backend: secret
        application-name: myapp
      config:
        lifecycle:
          enabled: true
          min-renewal: 10s
          expiry-threshold: 1m

  # Database Configuration (using H2 for demo)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # H2 Console (for development)
  h2:
    console:
      enabled: true

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,vault
  endpoint:
    health:
      show-details: always

# Application-specific configuration (values from Vault)
app:
  api:
    external-key: ${vault.secret.myapp.api.external-api-key:default-key}
    jwt-secret: ${vault.secret.myapp.api.jwt-secret:default-secret}

  features:
    vault-integration: true
    database-enabled: true

# Logging Configuration
logging:
  level:
    com.example: DEBUG
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"